/**
 * core.ts — pi-free logic of the /commit command: git access, `pi -p`
 * generation and model memory. Self-contained — no pi imports and no
 * cross-extension imports — so it can be unit-tested with `npm test`
 * (node --test *.test.ts) outside pi's extension loader. index.ts wires the
 * flow, ui.ts holds the dialogs.
 */

import { execFile, execFileSync, spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

// ---- pi CLI generation ------------------------------------------------------
//
// The commit message is generated by a `pi -p` child process (the `pi`
// command) instead of an in-process subagent: deterministic flags, no
// dependency on the pi-subagents service, and the model is chosen per run.
// The system prompt below carries the rules that used to live in
// agents/commit.md (which was deleted); the staged diff is piped on stdin, so
// the child runs with --no-tools.

export const GENERATION_TIMEOUT_MS = 120_000;

/** Short argv message; the details (file list + staged diff) are piped on stdin. */
export const TASK_HEADER = "为以下已暂存文件生成 commit message,文件列表和 staged diff 见 stdin";

/**
 * System prompt for the `pi -p` generator. Formerly agents/commit.md
 * (prompt_mode: replace) — now embedded here, single source of truth.
 */
export const COMMIT_SYSTEM_PROMPT = `You are a commit message generator. Your only job is to produce a commit message for the user's request.

## Process

1. The staged changes are provided in the message below — inspect the file list and the staged diff.
2. Write a Conventional Commits message:
   - Format: \`type(scope): description\`
   - Types: \`feat\`, \`fix\`, \`chore\`, \`docs\`, \`style\`, \`refactor\`, \`test\`, \`ci\`, \`perf\`
   - Subject line under 72 characters, imperative mood
   - Add a body or bullets only when the change is complex enough to need them

## Rules

- Output ONLY the commit message text. Nothing before it, nothing after it.
- Do NOT add alternatives, variants, translations, or "a shorter version".
- Do NOT add explanations, notes, or commentary around the message.
- Do NOT wrap the message in code fences.
- The first line must be the Conventional Commits subject line.
- Never modify the repository — generation only.
- Do not ask questions. Do not wait for approval.`;

/** Build the `pi -p` argv. The task itself goes on stdin (see runPiGenerate). */
export function buildPiArgs(model: string, thinking?: string): string[] {
	const args = [
		"-p",
		"--model",
		model,
		"--system-prompt",
		COMMIT_SYSTEM_PROMPT,
		"--no-tools",
		"--no-extensions",
		"--no-skills",
		"--no-context-files",
		"--no-session",
	];
	if (thinking !== undefined) args.push("--thinking", thinking);
	args.push(TASK_HEADER);
	return args;
}

export interface GenerateResult {
	/** The generator's stdout (trimmed), when it exited 0. */
	message: string;
	/** Non-zero exit / spawn failure / timeout — mutually exclusive with message. */
	error?: string;
}

/**
 * Run `pi -p` with the system prompt above and task on stdin.
 * Resolves on exit; kills the child on timeout.
 */
export function runPiGenerate(opts: {
	model: string;
	thinking?: string;
	task: string;
	cwd: string;
	timeoutMs?: number;
}): Promise<GenerateResult> {
	const { model, thinking, task, cwd, timeoutMs = GENERATION_TIMEOUT_MS } = opts;
	return new Promise((resolve) => {
		const isWindows = process.platform === "win32";
		const piArgs = buildPiArgs(model, thinking);
		const piCommand = isWindows ? (process.env.ComSpec ?? "cmd.exe") : "pi";
		const commandArgs = isWindows
			? ["/d", "/s", "/c", "pi.cmd", ...piArgs]
			: piArgs;
		const child = spawn(piCommand, commandArgs, {
			cwd,
			stdio: ["pipe", "pipe", "pipe"],
		});
		let stdout = "";
		let stderr = "";
		let settled = false;
		let timedOut = false;

		const settle = (result: GenerateResult) => {
			if (settled) return;
			settled = true;
			clearTimeout(timer);
			resolve(result);
		};

		const timer = setTimeout(() => {
			timedOut = true;
			settle({ message: "", error: "生成超时" });
			if (process.platform === "win32" && child.pid) {
				execFile("taskkill", ["/pid", String(child.pid), "/t", "/f"], () => {
					settle({ message: "", error: "生成超时" });
				});
			} else {
				child.kill("SIGKILL");
			}
		}, timeoutMs);

		child.stdout.on("data", (chunk: Buffer) => {
			stdout += chunk.toString();
		});
		child.stderr.on("data", (chunk: Buffer) => {
			stderr += chunk.toString();
		});
		child.on("error", (err) => {
			// e.g. ENOENT — the `pi` command is not on PATH.
			settle({ message: "", error: firstLineOf(err) });
		});
		child.on("close", (code) => {
			if (timedOut) return;
			if (code === 0) {
				settle({ message: stdout.trim() });
				return;
			}
			// pi prints model-resolution failures to stdout; stderr is a fallback.
			const detail = stdout.trim().split("\n")[0] || stderr.trim().split("\n")[0] || `pi 退出码 ${code}`;
			settle({ message: "", error: detail });
		});

		child.stdin.write(task);
		child.stdin.end();
	});
}

// ---- git --------------------------------------------------------------------

export interface StagedFile {
	status: string;
	path: string;
}

/** Parse `git diff --cached --name-status` output. Renames join old+new with →. */
export function parseStagedOutput(raw: string): StagedFile[] {
	return raw
		.trim()
		.split("\n")
		.filter((line) => line.length > 0)
		.map((line) => {
			const parts = line.split("\t");
			return { status: parts[0] ?? "", path: parts.slice(1).join(" → ") };
		});
}

/** Staged files of the repo at cwd. Throws on git errors. */
export function getStagedFiles(cwd: string): StagedFile[] {
	const out = execFileSync("git", ["diff", "--cached", "--name-status"], {
		cwd,
		encoding: "utf8",
	});
	return parseStagedOutput(out);
}

/** Staged diff text, piped to the generator. */
export function getStagedDiff(cwd: string): string {
	return execFileSync("git", ["diff", "--cached"], {
		cwd,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
	});
}

/** `git commit -m`; returns the first output line. Throws on failure. */
export function gitCommit(message: string, cwd: string): string {
	const output = execFileSync("git", ["commit", "-m", message], {
		cwd,
		encoding: "utf8",
	});
	return output.trim().split("\n")[0] ?? "";
}

// ---- prompt -----------------------------------------------------------------

/** The stdin payload for the generator: file list + staged diff. */
export function buildTask(files: StagedFile[], diff: string): string {
	const list = files.map((file) => `- ${file.status}  ${file.path}`).join("\n");
	return `文件列表:\n${list}\n\n<staged diff>\n${diff}`;
}

/** Line prefixes that open a model's meta commentary rather than the message. */
const META_LINE_PREFIXES = [
	"如需",
	"说明",
	"注意",
	"备注",
	"备选",
	"英文版",
	"Alternatively",
	"Translation:",
	"Note:",
	"Notes:",
];

/** True when a line looks like meta commentary (ignoring markdown decoration). */
function isMetaLine(line: string): boolean {
	const text = line.trim().replace(/^[#*>-]+\s*/, "");
	return META_LINE_PREFIXES.some((prefix) => text.startsWith(prefix));
}

/**
 * Reduce a generator reply to just the commit message.
 *
 * Well-behaved models return the message verbatim. Others append a fenced
 * "alternative" plus a trailing explanation — observed with deepseek-flash even
 * though COMMIT_SYSTEM_PROMPT forbids it. Three shapes are handled:
 *   1. the whole reply wrapped in one fence (tolerating an unclosed fence)
 *   2. a fence appearing later — keep only what precedes it
 *   3. a trailing meta section ("说明：…", "Note: …") — cut it off
 */
export function stripCodeFences(text: string): string {
	let out = text.trim();

	const whole = out.match(/^```[^\n]*\n([\s\S]*?)(?:```\s*)?$/);
	if (whole) return whole[1].trim();

	const fenceAt = out.search(/^```/m);
	if (fenceAt > 0) out = out.slice(0, fenceAt).trim();

	// Never treat the subject line itself as meta commentary.
	const lines = out.split("\n");
	const cut = lines.findIndex((line, index) => index > 0 && isMetaLine(line));
	if (cut > 0) out = lines.slice(0, cut).join("\n").trim();

	return out;
}

// ---- last model memory ------------------------------------------------------
//
// Remembers the last model chosen for /commit so the next run can lead the
// picker with it. Runtime state — last_model.json is gitignored.

/** Agent dir honouring PI_CODING_AGENT_DIR (same expansion as pi-subagents). */
export function getAgentDir(): string {
	const configured = process.env.PI_CODING_AGENT_DIR;
	if (configured === "~") return os.homedir();
	if (configured?.startsWith("~/")) {
		return path.join(os.homedir(), configured.slice(2));
	}
	return configured || path.join(os.homedir(), ".pi", "agent");
}

const LAST_MODEL_FILENAME = "last_model.json";

/** <agentDir>/extensions/commit/last_model.json */
export function lastModelPath(agentDir: string = getAgentDir()): string {
	return path.join(agentDir, "extensions", "commit", LAST_MODEL_FILENAME);
}

/** Last model used by /commit, or undefined when unset/missing/empty. */
export function readLastModel(agentDir: string = getAgentDir()): string | undefined {
	try {
		const raw = JSON.parse(fs.readFileSync(lastModelPath(agentDir), "utf8")) as {
			last_model?: unknown;
		};
		const value = raw?.last_model;
		return typeof value === "string" && value.length > 0 ? value : undefined;
	} catch {
		return undefined;
	}
}

/** Persist the last chosen model (single last_model field). */
export function writeLastModel(model: string, agentDir: string = getAgentDir()): void {
	fs.mkdirSync(path.dirname(lastModelPath(agentDir)), { recursive: true });
	fs.writeFileSync(
		lastModelPath(agentDir),
		JSON.stringify({ last_model: model }, null, 2) + "\n",
		"utf8",
	);
}

/**
 * Deduplicated model labels with `first` moved to the front. When
 * prependIfMissing, a `first` absent from the list is added at the top — used
 * for last_model, which must always lead the picker.
 */
export function orderModelOptions(
	labels: string[],
	first?: string,
	prependIfMissing = false,
): string[] {
	const options = [...new Set(labels)];
	if (first === undefined) return options;
	const index = options.indexOf(first);
	if (index > 0) {
		options.splice(index, 1);
		options.unshift(first);
	} else if (index === -1 && prependIfMissing) {
		options.unshift(first);
	}
	return options;
}

// ---- misc -------------------------------------------------------------------

/** First line of an error's most informative text (stderr for git, else message). */
export function firstLineOf(err: unknown): string {
	const stderr = (err as { stderr?: Buffer | string } | undefined)?.stderr;
	if (stderr !== undefined) {
		return stderr.toString().trim().split("\n")[0] ?? "";
	}
	return err instanceof Error ? (err.message.split("\n")[0] ?? "") : String(err);
}
