import { tmpdir } from "node:os";
import { join } from "node:path";

export const DEFAULT_SEARCH_TIMEOUT_MS = 15_000;
export const MIN_SEARCH_TIMEOUT_MS = 1_000;
export const MAX_SEARCH_TIMEOUT_MS = 120_000;
export const DEFAULT_FETCH_TIMEOUT_MS = 15_000;
export const MIN_FETCH_TIMEOUT_MS = 1_000;
export const MAX_FETCH_TIMEOUT_MS = 120_000;
export const DEFAULT_MAX_RESULTS = 5;
export const MIN_MAX_RESULTS = 1;
export const MAX_MAX_RESULTS = 10;
export const MAX_QUERY_LENGTH = 2_000;
export const MAX_URL_LENGTH = 8_192;
export const MAX_DOMAIN_COUNT = 20;
export const MAX_DOMAIN_LENGTH = 253;
export const MAX_RECENCY_DAYS = 3_650;
export const MAX_RESPONSE_BYTES = 1_048_576;
export const MAX_FETCH_CONTENT_BYTES = 1_048_576;
export const MAX_FETCH_OUTPUT_BYTES = 50 * 1_024;
export const MAX_OUTPUT_BYTES = MAX_FETCH_OUTPUT_BYTES;
export const MAX_FETCH_OUTPUT_LINES = 2_000;
export const MAX_FETCH_PREVIEW_BYTES = 8 * 1_024;
export const MAX_GITHUB_COMMAND_OUTPUT_BYTES = 2 * 1_024 * 1_024;
export const MAX_GITHUB_TREE_ENTRIES = 200;
export const MAX_GITHUB_README_BYTES = 8 * 1_024;
export const MAX_GITHUB_SESSION_CLONES = 32;
export const TEMP_SPOOL_TTL_MS = 24 * 60 * 60 * 1_000;
export const DEFAULT_GITHUB_ENABLED = true;
export const DEFAULT_GITHUB_MAX_REPO_SIZE_MB = 350;
export const MIN_GITHUB_REPO_SIZE_MB = 1;
export const MAX_GITHUB_REPO_SIZE_MB = 10_240;
export const DEFAULT_GITHUB_CLONE_TIMEOUT_SECONDS = 30;
export const MIN_GITHUB_CLONE_TIMEOUT_SECONDS = 5;
export const MAX_GITHUB_CLONE_TIMEOUT_SECONDS = 600;
export const DEFAULT_GITHUB_CLONE_PATH = join(tmpdir(), "pi-web-tools-github");
